### ISSUE TITLE
Update ReadME documentation

### ISSUE THREAD

**Issue by SWi1** [aoliver44/nutrition_tools#1]
Update README with specific language that subject_id should not contain alphabetic characters. 

__Case Example__
- Error during generic_combine command when subject_ids across input files have study abbreviation labels still attached (Ex: 'P12A'). Removal of alphabetic characters from subject_id (Ex: 'P12A' becomes '12') allowed command to fully run. 
- _Note_: taxaHFE works okay with abbreviation labels attached

**Comment by aoliver44** [comment]
THANK YOU! 
I think this is fixed now. The main relevant code is in generic_combine.R, here:
```
## add a numeric_id for the subject_id. If the subject_id has characters, it
## seems to trip up mikropML (subject_id gets one-hot encoded)
full_merge_dedup_pre_cor <- full_merge_dedup_pre_cor %>%
  dplyr::mutate(., subject_index = as.numeric(factor(.data[[opt$subject_identifier]])))

subject_index_mapping <- full_merge_dedup_pre_cor %>%
  dplyr::select(., opt$subject_identifier, subject_index)

full_merge_dedup_pre_cor <- full_merge_dedup_pre_cor %>%
  dplyr::select(., -opt$subject_identifier)

```

I've done some pretty limited testing and so far, so good. Please let me know if i broke something else haha.
